### ISSUE TITLE
ntdll64.lib

### ISSUE THREAD

**Issue by SolomonSklash** [zodiacon/NativeApps#2]
Can I ask where you are getting `ntdll64.lib` in your `listprivs` project? I am create a BootExec program, and if I use any CRT functions exported from `ntdll.dll`, the linker can't find them. I notice the same behavior if I use a CRT function in your `simple` project, which seems to be overcome by using `ntdll64.lib`.

My machine does not have it installed, and google does not show much. I tried creating my own from a dump of the exports of `ntdll.dll` and using `lib.exe` to create it, but I bluescreen when my excutable runs.

Thanks!

**Comment by zodiacon** [comment]
I found it somewhere (don't recall where) on Github, essentially this is LIB file generated by using the correct prototypes for the functions. You can either use it, or build it yourself with Visual Studio by listing the functions with dummy implementation just to get the LIB file.
Alternatively, you can always bind dynamically with LdrLoadLibrary and LdrGetProcedureAddress.

**Comment by SolomonSklash** [comment]
Thanks for the quick update! Turns out I was missing `LIBRARY ntdll.dll` at the top of my `.def` file. Works great now.
